export { default as OurServiceImage } from "./ourServiceImage.png";
export { default as WhySolarImage } from "./whySolarImage.png";
export { default as OurProcessImage } from "./OurProcessImage.png";
export { default as OurPurposeImage } from "./ourPurposeImage.png";
export { default as WhatClientSayImage } from "./whatOurClientSayImage.png";
export { default as ContactUsImage } from "./contactUsImage.png";
export { default as ExploreServicesBgImage } from "./ExploreServicesBgImage.png";
export { default as ProjectOverviewBgImage } from "./ProjectOverviewBgImage.png";
export { default as AboutUsEmpoweringImage } from "./AboutUsEmpoweringImage.png";
